name: processRegistry
description: A library that manages and wrangle process that execute in with their own heap space and eventloop.
version: 0.0.1
author: Ray King & Ji Young Lee
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
   collection: "^1.5.1"
   path: "^1.3.9"
   pub_semver: "^1.2.4"
   quiver_async: "^1.0.0"
   quiver_check: "^1.0.0"
   quiver_hashcode: "^1.0.0"
   quiver_iterables: "^1.0.0"
   quiver_optional: "^1.0.0"
   quiver_strings: "^1.0.0"
   uuid: "0.5.0"
   async: "^1.9.0"

dev_dependencies:
  coverage: "^0.7.3"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.9.0"
  test: '>=0.12.0 <0.13.0'
